import * as path from 'path'

export const LOGO_PATH = path.resolve(__dirname, './static/backgroundStart.svg')
export const USB_ON_PATH = path.resolve(__dirname, 'static/i_usb_connection_on.svg')
export const USB_OFF_PATH = path.resolve(__dirname, 'static/i_usb_connection_off.svg')
export const BITCOIN_PATH = path.resolve(__dirname, 'static/bitcoin.svg')
export const LITECOIN_PATH = path.resolve(__dirname, 'static/litecoin.svg')
export const ETHEREUM_PATH = path.resolve(__dirname, 'static/ether.svg')
export const ARROW_UP_PATH = path.resolve(__dirname, 'static/i_arr_money_in.svg')
export const ARROW_DOWN_PATH = path.resolve(__dirname, 'static/i_arr_money_out.svg')
export const REFRESH_BUTTON_PATH = path.resolve(__dirname, 'static/i_update.svg')
export const TRANSACTION_SUCCESS = path.resolve(__dirname, 'static/Group5.svg')
export const LOGO_SMALL = path.resolve(__dirname, 'static/logo_small.svg')
export const BTN_MENU_PATH = path.resolve(__dirname, 'static/btn_menu.svg')
export const BTC_ICON = path.resolve(__dirname, 'static/icon_BTC.svg')
export const LTC_ICON = path.resolve(__dirname, 'static/icon_LTC.svg')
export const ETH_ICON = path.resolve(__dirname, 'static/icon_ETH.svg')
export const XRP_ICON = path.resolve(__dirname, 'static/icon_XRP.svg')
// export const BTC_ICON = path.resolve(__dirname, 'assets/images/icon_BTC.svg')
// export const LTC_ICON  = path.resolve(__dirname, 'assets/images/icon_LTC.svg')
// export const ETH_ICON  = path.resolve(__dirname, 'assets/images/icon_ETH.svg')
// export const XRP_ICON = path.resolve(__dirname, 'assets/images/icon_XRP.svg')